# Generated by Django 4.1.3 on 2023-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIv1', '0002_remove_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='pdf',
            field=models.FileField(default=1, upload_to='uploadedPdf/'),
            preserve_default=False,
        ),
    ]
