# Generated by Django 4.1.3 on 2023-03-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIv1", "0005_alter_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="summaryFilePath",
            field=models.CharField(default="alpana", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="website",
            name="textFilePath",
            field=models.CharField(default="alpana", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="website",
            name="pdf",
            field=models.FileField(upload_to="APIv1/uploadedPdf/"),
        ),
    ]
